# Generated by Django 5.2.17 on 2026-09-27 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='合同编号')),
                ('customer', models.CharField(max_length=128, verbose_name='客户')),
                ('signed_on', models.DateField(verbose_name='签订日期')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='合同固定对价')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(verbose_name='开票日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='开票金额(不含税口径)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '开票',
                'verbose_name_plural': '开票',
                'ordering': ['issued_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField(verbose_name='收款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='收款金额')),
                ('is_prepayment', models.BooleanField(default=False, verbose_name='预收(服务未开通)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '收款',
                'verbose_name_plural': '收款',
                'ordering': ['received_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='合同项编号')),
                ('name', models.CharField(max_length=128, verbose_name='履约义务')),
                ('obligation_type', models.CharField(choices=[('subscription', '账号订阅'), ('implementation', '一次性实施'), ('usage', '按量服务')], max_length=16, verbose_name='类型')),
                ('ssp_unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='SSP 单价')),
                ('ssp_quantity', models.IntegerField(default=1, verbose_name='SSP 计量数量(月/项/预估用量)')),
                ('standalone_selling_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='独立售价 SSP 合计')),
                ('allocated_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='分摊交易价格')),
                ('service_start', models.DateField(blank=True, null=True, verbose_name='服务开始日')),
                ('service_end', models.DateField(blank=True, null=True, verbose_name='服务结束日')),
                ('usage_unit', models.CharField(blank=True, default='', max_length=16, verbose_name='用量单位')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='accounting.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '履约义务',
                'verbose_name_plural': '履约义务',
                'ordering': ['contract_id', 'code'],
                'unique_together': {('contract', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AcceptanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_on', models.DateField(verbose_name='验收日期')),
                ('portion', models.DecimalField(decimal_places=4, help_text='0~1，例如部分验收 0.6', max_digits=6, verbose_name='验收比例')),
                ('document_ref', models.CharField(max_length=64, verbose_name='验收单据号')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obligation', models.ForeignKey(limit_choices_to={'obligation_type': 'implementation'}, on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_evidences', to='accounting.performanceobligation', verbose_name='实施义务')),
            ],
            options={
                'verbose_name': '验收证据',
                'verbose_name_plural': '验收证据',
                'ordering': ['accepted_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_month', models.DateField(verbose_name='用量所属月份(取每月1日)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='用量')),
                ('source_ref', models.CharField(max_length=64, verbose_name='用量单据号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obligation', models.ForeignKey(limit_choices_to={'obligation_type': 'usage'}, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='accounting.performanceobligation', verbose_name='按量义务')),
            ],
            options={
                'verbose_name': '用量记录',
                'verbose_name_plural': '用量记录',
                'ordering': ['usage_month'],
                'unique_together': {('obligation', 'usage_month')},
            },
        ),
        migrations.CreateModel(
            name='RevenueRecognitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='确认期间起')),
                ('period_end', models.DateField(verbose_name='确认期间止/确认依据日')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='确认金额')),
                ('status', models.CharField(choices=[('recognized', '已确认'), ('pending', '待确认')], max_length=16, verbose_name='状态')),
                ('basis', models.CharField(max_length=255, verbose_name='确认依据')),
                ('evidence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_line', to='accounting.acceptanceevidence')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_lines', to='accounting.performanceobligation', verbose_name='履约义务')),
                ('usage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_line', to='accounting.usagerecord')),
            ],
            options={
                'verbose_name': '收入确认计划行',
                'verbose_name_plural': '收入确认计划行',
                'ordering': ['period_end', 'id'],
                'indexes': [models.Index(fields=['status'], name='accounting__status_325be6_idx')],
            },
        ),
    ]
