# Generated by Django 4.2.30 on 2026-09-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='合同编号')),
                ('customer', models.CharField(max_length=120, verbose_name='客户名称')),
                ('signed_on', models.DateField(verbose_name='签订日期')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='合同交易价格')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='行序')),
                ('name', models.CharField(max_length=120, verbose_name='义务名称')),
                ('line_type', models.CharField(choices=[('SUBSCRIPTION', '账号订阅'), ('IMPLEMENTATION', '一次性实施'), ('USAGE', '按量服务')], max_length=20, verbose_name='义务类型')),
                ('ssp', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='独立售价 SSP')),
                ('allocated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='分摊后交易价格')),
                ('service_start', models.DateField(blank=True, null=True, verbose_name='服务开始日')),
                ('service_end', models.DateField(blank=True, null=True, verbose_name='服务结束日')),
                ('estimated_units', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估总量')),
                ('unit_label', models.CharField(blank=True, default='', max_length=20, verbose_name='计量单位')),
                ('usage_unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='分摊单价')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='revrec.contract')),
            ],
            options={
                'ordering': ['contract', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='所属期间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='用量')),
                ('recorded_on', models.DateField(auto_now_add=True, verbose_name='录入日期')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='revrec.contractline')),
            ],
            options={
                'ordering': ['line', 'period', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='所属期间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('status', models.CharField(choices=[('PLANNED', '待确认'), ('RECOGNIZED', '已确认')], default='PLANNED', max_length=12, verbose_name='状态')),
                ('basis_type', models.CharField(choices=[('TIME_ELAPSED', '期间服务已提供（按月）'), ('ACCEPTANCE', '验收证据'), ('USAGE', '已录入用量')], max_length=20, verbose_name='确认依据')),
                ('basis_note', models.CharField(blank=True, default='', max_length=200, verbose_name='依据说明')),
                ('recognized_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='revrec.contractline')),
            ],
            options={
                'ordering': ['line', 'period', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField(verbose_name='收款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='收款金额')),
                ('reference', models.CharField(blank=True, default='', max_length=60, verbose_name='收款单号')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='revrec.contract')),
            ],
            options={
                'ordering': ['contract', 'received_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcceptanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_on', models.DateField(verbose_name='验收日期')),
                ('reference', models.CharField(max_length=60, verbose_name='验收单号')),
                ('note', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='revrec.contractline')),
            ],
        ),
    ]
